# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentAdvisorAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentmodel',
            old_name='score',
            new_name='Score',
        ),
    ]
