# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentAdvisorAPP', '0002_auto_20161221_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentmodel',
            old_name='Score',
            new_name='score',
        ),
    ]
