# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentAdvisorAPP', '0003_auto_20161221_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmodel',
            name='score',
        ),
    ]
