# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentAdvisorAPP', '0004_remove_investmentmodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmodel',
            name='inputA',
            field=models.FloatField(),
        ),
    ]
