# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentAdvisorAPP', '0005_auto_20161222_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('transactionNumEver', models.IntegerField()),
                ('transactionNum12', models.IntegerField()),
                ('transactionNum6', models.IntegerField()),
                ('transactionPurchaseEver', models.FloatField()),
                ('transactionPurchase12', models.FloatField()),
                ('transactionPurchase6', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_FICO', models.IntegerField()),
                ('BorrowerExp', models.IntegerField()),
                ('LTV', models.FloatField()),
                ('PersonalGuarantee', models.BooleanField()),
                ('Coupon', models.FloatField()),
                ('Grade', models.CharField(max_length=5)),
            ],
        ),
    ]
